In [72]:
import re
import pandas as pd

In [73]:
f = open("WhatsApp Chat with 7_8pm AIML Poush 04.txt","r", encoding = "utf-8")

In [74]:
data = f.read()

In [ ]:
print(data)

In [76]:
print(type(data))

<class 'str'>

<h3>1) Preprocessing</h3>

In [77]:
# For 12-hour format (most common)
pattern = r"\d{1,2}/\d{1,2}/\d{4},\s\d{1,2}:\d{2}\u202f[ap]m\s-\s"

In [78]:
messages = re.split(pattern, data)[1:]
len(message)

0

In [79]:
dates = re.findall(pattern, data)
dates

['17/12/2025, 10:05\u202fam - ',
 '17/12/2025, 10:05\u202fam - ',
 '17/12/2025, 10:05\u202fam - ',
 '17/12/2025, 10:07\u202fam - ',
 '17/12/2025, 1:04\u202fpm - ',
 '17/12/2025, 1:10\u202fpm - ',
 '17/12/2025, 1:16\u202fpm - ',
 '17/12/2025, 1:17\u202fpm - ',
 '19/12/2025, 11:07\u202fam - ',
 '19/12/2025, 6:55\u202fpm - ',
 '19/12/2025, 7:30\u202fpm - ',
 '19/12/2025, 7:30\u202fpm - ',
 '20/12/2025, 5:39\u202fpm - ',
 '21/12/2025, 7:01\u202fpm - ',
 '21/12/2025, 7:02\u202fpm - ',
 '21/12/2025, 7:08\u202fpm - ',
 '21/12/2025, 7:10\u202fpm - ',
 '22/12/2025, 7:02\u202fpm - ',
 '22/12/2025, 7:06\u202fpm - ',
 '22/12/2025, 7:55\u202fpm - ',
 '23/12/2025, 8:21\u202fam - ',
 '23/12/2025, 9:03\u202fam - ',
 '23/12/2025, 9:04\u202fam - ',
 '23/12/2025, 7:01\u202fpm - ',
 '23/12/2025, 7:02\u202fpm - ',
 '23/12/2025, 7:02\u202fpm - ',
 '24/12/2025, 6:59\u202fpm - ',
 '24/12/2025, 7:56\u202fpm - ',
 '25/12/2025, 5:44\u202fpm - ',
 '25/12/2025, 6:07\u202fpm - ',
 '25/12/2025, 6:08\u202fpm - ',
 '26/12/2025, 3:44\u202fpm - ',
 '26/12/2025, 3:43\u202fpm - ',
 '26/12/2025, 3:44\u202fpm - ',
 '26/12/2025, 3:45\u202fpm - ',
 '26/12/2025, 3:46\u202fpm - ',
 '26/12/2025, 7:00\u202fpm - ',
 '26/12/2025, 7:00\u202fpm - ',
 '26/12/2025, 7:02\u202fpm - ',
 '26/12/2025, 7:03\u202fpm - ',
 '28/12/2025, 7:01\u202fpm - ',
 '29/12/2025, 7:01\u202fpm - ',
 '29/12/2025, 7:02\u202fpm - ',
 '29/12/2025, 7:02\u202fpm - ',
 '29/12/2025, 7:58\u202fpm - ',
 '30/12/2025, 7:01\u202fpm - ',
 '30/12/2025, 7:57\u202fpm - ',
 '31/12/2025, 12:57\u202fpm - ',
 '31/12/2025, 7:18\u202fpm - ',
 '31/12/2025, 7:18\u202fpm - ',
 '31/12/2025, 7:18\u202fpm - ',
 '31/12/2025, 7:38\u202fpm - ',
 '31/12/2025, 7:39\u202fpm - ',
 '31/12/2025, 7:40\u202fpm - ',
 '31/12/2025, 8:17\u202fpm - ',
 '01/01/2026, 5:57\u202fpm - ',
 '01/01/2026, 7:02\u202fpm - ',
 '01/01/2026, 7:02\u202fpm - ',
 '01/01/2026, 7:55\u202fpm - ',
 '02/01/2026, 8:21\u202fam - ',
 '02/01/2026, 8:21\u202fam - ',
 '02/01/2026, 7:01\u202fpm - ',
 '04/01/2026, 9:27\u202fam - ',
 '04/01/2026, 12:38\u202fpm - ',
 '04/01/2026, 7:00\u202fpm - ',
 '04/01/2026, 7:37\u202fpm - ',
 '04/01/2026, 7:37\u202fpm - ',
 '05/01/2026, 7:00\u202fpm - ',
 '05/01/2026, 7:06\u202fpm - ',
 '05/01/2026, 7:57\u202fpm - ',
 '05/01/2026, 7:58\u202fpm - ',
 '06/01/2026, 7:00\u202fpm - ',
 '06/01/2026, 7:56\u202fpm - ',
 '07/01/2026, 7:02\u202fpm - ',
 '07/01/2026, 7:56\u202fpm - ',
 '08/01/2026, 7:03\u202fpm - ',
 '08/01/2026, 7:22\u202fpm - ',
 '08/01/2026, 8:07\u202fpm - ',
 '08/01/2026, 8:08\u202fpm - ',
 '09/01/2026, 6:19\u202fpm - ',
 '09/01/2026, 6:19\u202fpm - ',
 '09/01/2026, 6:22\u202fpm - ',
 '09/01/2026, 7:07\u202fpm - ',
 '09/01/2026, 7:08\u202fpm - ',
 '11/01/2026, 6:35\u202fpm - ',
 '11/01/2026, 7:00\u202fpm - ',
 '11/01/2026, 7:01\u202fpm - ',
 '11/01/2026, 7:13\u202fpm - ',
 '11/01/2026, 7:24\u202fpm - ',
 '11/01/2026, 7:32\u202fpm - ',
 '11/01/2026, 7:34\u202fpm - ',
 '11/01/2026, 7:56\u202fpm - ',
 '12/01/2026, 8:13\u202fam - ',
 '12/01/2026, 9:31\u202fam - ',
 '12/01/2026, 10:31\u202fam - ',
 '12/01/2026, 6:28\u202fpm - ',
 '12/01/2026, 6:59\u202fpm - ',
 '12/01/2026, 6:59\u202fpm - ',
 '12/01/2026, 7:57\u202fpm - ',
 '13/01/2026, 1:01\u202fpm - ',
 '13/01/2026, 1:02\u202fpm - ',
 '13/01/2026, 1:03\u202fpm - ',
 '13/01/2026, 1:04\u202fpm - ',
 '13/01/2026, 2:11\u202fpm - ',
 '13/01/2026, 2:33\u202fpm - ',
 '13/01/2026, 6:21\u202fpm - ',
 '13/01/2026, 6:22\u202fpm - ',
 '13/01/2026, 6:27\u202fpm - ',
 '13/01/2026, 6:34\u202fpm - ',
 '13/01/2026, 6:59\u202fpm - ',
 '14/01/2026, 5:50\u202fpm - ',
 '14/01/2026, 6:09\u202fpm - ',
 '14/01/2026, 6:09\u202fpm - ',
 '15/01/2026, 3:09\u202fpm - ',
 '15/01/2026, 3:09\u202fpm - ',
 '15/01/2026, 3:10\u202fpm - ',
 '15/01/2026, 3:45\u202fpm - ',
 '15/01/2026, 5:12\u202fpm - ',
 '16/01/2026, 6:58\u202fpm - ',
 '16/01/2026, 7:19\u202fpm - ',
 '16/01/2026, 7:57\u202fpm - ',
 '16/01/2026, 7:57\u202fpm - ',
 '18/01/2026, 5:43\u202fpm - ',
 '18/01/2026, 5:44\u202fpm - ',
 '18/01/2026, 5:51\u202fpm - ',
 '18/01/2026, 5:53\u202fpm - ',
 '18/01/2026, 6:04\u202fpm - ',
 '18/01/2026, 6:04\u202fpm - ',
 '18/01/2026, 6:58\u202fpm - ',
 '19/01/2026, 6:58\u202fpm - ',
 '20/01/2026, 1:18\u202fpm - ',
 '20/01/2026, 1:20\u202fpm - ',
 '20/01/2026, 1:23\u202fpm - ',
 '20/01/2026, 6:59\u202fpm - ',
 '20/01/2026, 8:00\u202fpm - ',
 '21/01/2026, 7:00\u202fpm - ',
 '22/01/2026, 8:13\u202fam - ',
 '22/01/2026, 9:49\u202fam - ',
 '22/01/2026, 12:39\u202fpm - ',
 '22/01/2026, 7:00\u202fpm - ',
 '23/01/2026, 7:02\u202fpm - ',
 '23/01/2026, 7:56\u202fpm - ',
 '25/01/2026, 7:01\u202fpm - ',
 '25/01/2026, 7:22\u202fpm - ',
 '25/01/2026, 7:22\u202fpm - ',
 '26/01/2026, 7:04\u202fpm - ',
 '27/01/2026, 7:03\u202fpm - ',
 '28/01/2026, 9:08\u202fam - ',
 '28/01/2026, 7:01\u202fpm - ',
 '28/01/2026, 7:47\u202fpm - ',
 '29/01/2026, 7:04\u202fpm - ',
 '30/01/2026, 7:00\u202fpm - ',
 '01/02/2026, 7:00\u202fpm - ',
 '02/02/2026, 6:59\u202fpm - ',
 '02/02/2026, 7:05\u202fpm - ',
 '02/02/2026, 7:38\u202fpm - ',
 '02/02/2026, 7:42\u202fpm - ',
 '02/02/2026, 7:43\u202fpm - ',
 '02/02/2026, 8:06\u202fpm - ',
 '02/02/2026, 8:06\u202fpm - ',
 '02/02/2026, 8:06\u202fpm - ',
 '03/02/2026, 7:04\u202fpm - ',
 '03/02/2026, 7:49\u202fpm - ',
 '04/02/2026, 7:01\u202fpm - ',
 '05/02/2026, 7:00\u202fpm - ',
 '05/02/2026, 7:54\u202fpm - ',
 '06/02/2026, 7:04\u202fpm - ',
 '06/02/2026, 9:36\u202fpm - ',
 '08/02/2026, 7:02\u202fpm - ',
 '08/02/2026, 7:07\u202fpm - ',
 '08/02/2026, 7:07\u202fpm - ',
 '08/02/2026, 7:22\u202fpm - ',
 '08/02/2026, 7:22\u202fpm - ',
 '08/02/2026, 7:22\u202fpm - ',
 '08/02/2026, 7:22\u202fpm - ',
 '09/02/2026, 6:58\u202fpm - ',
 '09/02/2026, 7:12\u202fpm - ',
 '09/02/2026, 7:56\u202fpm - ',
 '10/02/2026, 7:04\u202fpm - ',
 '10/02/2026, 7:05\u202fpm - ',
 '10/02/2026, 7:06\u202fpm - ',
 '10/02/2026, 7:45\u202fpm - ',
 '11/02/2026, 7:04\u202fpm - ',
 '11/02/2026, 7:15\u202fpm - ',
 '11/02/2026, 7:15\u202fpm - ',
 '11/02/2026, 7:32\u202fpm - ',
 '12/02/2026, 6:51\u202fpm - ',
 '12/02/2026, 7:00\u202fpm - ',
 '12/02/2026, 7:00\u202fpm - ',
 '12/02/2026, 7:01\u202fpm - ',
 '13/02/2026, 7:02\u202fpm - ',
 '13/02/2026, 7:54\u202fpm - ',
 '15/02/2026, 6:20\u202fpm - ',
 '15/02/2026, 6:23\u202fpm - ',
 '16/02/2026, 7:01\u202fpm - ',
 '16/02/2026, 7:55\u202fpm - ',
 '17/02/2026, 7:03\u202fpm - ',
 '18/02/2026, 12:35\u202fpm - ',
 '18/02/2026, 7:03\u202fpm - ',
 '18/02/2026, 7:03\u202fpm - ',
 '18/02/2026, 7:29\u202fpm - ',
 '18/02/2026, 7:30\u202fpm - ',
 '19/02/2026, 6:27\u202fpm - ',
 '19/02/2026, 6:29\u202fpm - ',
 '19/02/2026, 7:03\u202fpm - ',
 '19/02/2026, 7:05\u202fpm - ',
 '19/02/2026, 7:05\u202fpm - ',
 '22/02/2026, 7:02\u202fpm - ',
 '22/02/2026, 7:17\u202fpm - ',
 '22/02/2026, 7:21\u202fpm - ',
 '23/02/2026, 7:04\u202fpm - ',
 '24/02/2026, 7:01\u202fpm - ',
 '25/02/2026, 7:01\u202fpm - ',
 '25/02/2026, 7:12\u202fpm - ',
 '26/02/2026, 7:05\u202fpm - ',
 '26/02/2026, 7:48\u202fpm - ',
 '26/02/2026, 7:58\u202fpm - ',
 '26/02/2026, 8:00\u202fpm - ',
 '27/02/2026, 7:04\u202fpm - ',
 '01/03/2026, 5:52\u202fpm - ',
 '01/03/2026, 5:56\u202fpm - ',
 '01/03/2026, 5:59\u202fpm - ',
 '01/03/2026, 6:01\u202fpm - ',
 '01/03/2026, 6:01\u202fpm - ',
 '01/03/2026, 6:03\u202fpm - ',
 '01/03/2026, 6:07\u202fpm - ',
 '01/03/2026, 6:08\u202fpm - ',
 '01/03/2026, 7:54\u202fpm - ',
 '02/03/2026, 7:01\u202fpm - ',
 '03/03/2026, 6:03\u202fpm - ',
 '03/03/2026, 6:04\u202fpm - ',
 '03/03/2026, 6:04\u202fpm - ',
 '03/03/2026, 6:36\u202fpm - ',
 '03/03/2026, 6:45\u202fpm - ',
 '03/03/2026, 7:02\u202fpm - ',
 '04/03/2026, 7:02\u202fpm - ',
 '05/03/2026, 4:20\u202fpm - ',
 '06/03/2026, 6:19\u202fpm - ',
 '06/03/2026, 6:19\u202fpm - ',
 '06/03/2026, 7:01\u202fpm - ',
 '06/03/2026, 7:10\u202fpm - ',
 '07/03/2026, 10:03\u202fpm - ',
 '08/03/2026, 6:59\u202fpm - ',
 '08/03/2026, 7:52\u202fpm - ',
 '09/03/2026, 5:36\u202fpm - ',
 '09/03/2026, 5:36\u202fpm - ',
 '10/03/2026, 7:00\u202fpm - ',
 '10/03/2026, 8:02\u202fpm - ',
 '11/03/2026, 7:01\u202fpm - ',
 '11/03/2026, 8:03\u202fpm - ',
 '11/03/2026, 8:04\u202fpm - ',
 '12/03/2026, 7:01\u202fpm - ',
 '12/03/2026, 7:54\u202fpm - ',
 '12/03/2026, 7:54\u202fpm - ',
 '13/03/2026, 5:14\u202fpm - ',
 '13/03/2026, 5:14\u202fpm - ',
 '13/03/2026, 5:22\u202fpm - ',
 '15/03/2026, 4:41\u202fpm - ',
 '15/03/2026, 4:45\u202fpm - ',
 '16/03/2026, 9:23\u202fam - ',
 '16/03/2026, 7:01\u202fpm - ',
 '16/03/2026, 7:05\u202fpm - ',
 '16/03/2026, 7:53\u202fpm - ',
 '16/03/2026, 7:54\u202fpm - ',
 '17/03/2026, 11:11\u202fam - ',
 '17/03/2026, 11:28\u202fam - ',
 '17/03/2026, 7:01\u202fpm - ',
 '17/03/2026, 7:09\u202fpm - ',
 '18/03/2026, 7:04\u202fpm - ',
 '19/03/2026, 6:40\u202fpm - ',
 '19/03/2026, 6:41\u202fpm - ',
 '19/03/2026, 6:42\u202fpm - ',
 '20/03/2026, 7:03\u202fpm - ',
 '20/03/2026, 7:15\u202fpm - ',
 '20/03/2026, 7:16\u202fpm - ',
 '20/03/2026, 7:16\u202fpm - ',
 '20/03/2026, 8:13\u202fpm - ',
 '20/03/2026, 8:14\u202fpm - ',
 '22/03/2026, 7:01\u202fpm - ',
 '22/03/2026, 7:59\u202fpm - ',
 '23/03/2026, 7:02\u202fpm - ',
 '24/03/2026, 7:02\u202fpm - ',
 '25/03/2026, 8:16\u202fam - ',
 '25/03/2026, 8:29\u202fam - ',
 '25/03/2026, 8:39\u202fam - ',
 '25/03/2026, 8:40\u202fam - ',
 '25/03/2026, 8:41\u202fam - ',
 '29/03/2026, 6:15\u202fpm - ',
 '30/03/2026, 7:15\u202fpm - ',
 '30/03/2026, 7:15\u202fpm - ',
 '30/03/2026, 7:22\u202fpm - ']

In [81]:
df = pd.DataFrame({"user_message": messages, "message_date": dates})

df["message_date"] = df["message_date"].str.replace(r"\s[–-]\s$", "", regex=True)

df["datetime"] = pd.to_datetime(df["message_date"], format="%d/%m/%Y, %I:%M\u202f%p")

df = df.drop(columns=["message_date"]).rename(columns={"datetime": "date"})


print(df.head())

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-12-17 10:05:00
1  Evolve IT Hub created group "7_8pm AIML Poush ... 2025-12-17 10:05:00
2                          Evolve IT Hub added you\n 2025-12-17 10:05:00
3          Evolve IT Hub changed this group's icon\n 2025-12-17 10:07:00
4                   Amrit: Class kahile dekhi ho??\n 2025-12-17 13:04:00

In [82]:
df.shape # Numbers of message is in the group.

(291, 2)

In [83]:
users = []
messages = []
for message in df['user_message']:  # Fixed: removed space in column name
    entry = re.split('([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')  # Fixed: added dot before append
        messages.append(entry[0])

df['user'] = users
df['message'] = messages  
df.drop(columns=['user_message'], inplace=True)  
df.head()

,date,user,message
0,2025-12-17 10:05:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2025-12-17 10:05:00,group_notification,"Evolve IT Hub created group ""7_8pm AIML Poush ..."
2,2025-12-17 10:05:00,group_notification,Evolve IT Hub added you\n
3,2025-12-17 10:07:00,group_notification,Evolve IT Hub changed this group's icon\n
4,2025-12-17 13:04:00,Amrit,Class kahile dekhi ho??\n

In [84]:
df['year'] = df['date'].dt.year #Exctracting the year from dataset.

In [85]:
df['date'].dt.year

0      2025
1      2025
2      2025
3      2025
4      2025
       ...
286    2026
287    2026
288    2026
289    2026
290    2026
Name: date, Length: 291, dtype: int32

In [86]:
df.head()

,date,user,message,year
0,2025-12-17 10:05:00,group_notification,Messages and calls are end-to-end encrypted. O...,2025
1,2025-12-17 10:05:00,group_notification,"Evolve IT Hub created group ""7_8pm AIML Poush ...",2025
2,2025-12-17 10:05:00,group_notification,Evolve IT Hub added you\n,2025
3,2025-12-17 10:07:00,group_notification,Evolve IT Hub changed this group's icon\n,2025
4,2025-12-17 13:04:00,Amrit,Class kahile dekhi ho??\n,2025

In [92]:
df['month'] = df['date'].dt.month_name()   #Exctracting the month from dataset.

In [103]:
df['date'] = pd.to_datetime(df['date'], dayfirst=True, errors='coerce')
df['day'] = df['date'].dt.day

In [107]:
df['hour'] = df['date'].dt.hour

In [108]:
df['minute'] = df['date'].dt.minute

In [109]:
df.head() #DataFrame is ready

,date,user,message,year,month,day,hour,minute
0,2025-12-17,group_notification,Messages and calls are end-to-end encrypted. O...,2025,December,17,0,0
1,2025-12-17,group_notification,"Evolve IT Hub created group ""7_8pm AIML Poush ...",2025,December,17,0,0
2,2025-12-17,group_notification,Evolve IT Hub added you\n,2025,December,17,0,0
3,2025-12-17,group_notification,Evolve IT Hub changed this group's icon\n,2025,December,17,0,0
4,2025-12-17,Amrit,Class kahile dekhi ho??\n,2025,December,17,0,0

<h3>2) Creating the App</h3>